###
POST  http://localhost:7100/category/ HTTP/1.1
content-type: application/json

{
    "name":"Camiseta",
    "active": true,
    "createdId": 8
}

###
GET  http://localhost:7100/category/ HTTP/1.

###
GET  http://localhost:7100/category/active HTTP/1.1

###
GET  http://localhost:7100/category/2 HTTP/1.1

###
PATCH  http://localhost:7100/category/2 HTTP/1.1
content-type: application/json

{
    "active": true
    
}

###
DELETE  http://localhost:7100/category/4 HTTP/1.1


###
POST  http://localhost:7100/category/list HTTP/1.1
content-type: application/json

{
    "name": "cam",
    "items": 10,
    "page": 1,
    "order": { "name": "ASC", "createdDate": "DESC"}
    
}