###
POST  http://localhost:7100/product/ HTTP/1.1
content-type: application/json

{
    "name":"Adidas da shoppee",
    "active": true,
    "createdId": 8,
    "image": "adidas.png",
    "fullPrice": 100,
    "description": "Camiseta da feirinha do Cocotá",
    "idCategory":5,
    "idBrand":4
}

###
GET  http://localhost:7100/product/ HTTP/1.1

###
GET  http://localhost:7100/product/active HTTP/1.1


###
GET  http://localhost:7100/product/2 HTTP/1.1

###
PATCH  http://localhost:7100/product/2 HTTP/1.1
content-type: application/json

{
    "salePrice": 400
    
}

###
DELETE  http://localhost:7100/product/2 HTTP/1.1


###
POST  http://localhost:7100/product/list HTTP/1.1
content-type: application/json

{
    "name": "",
    "items": 10,
    "page": 1,
    "order": { "fullPrice": "ASC"}
    
}

###
POST  http://localhost:7100/product/list-by-category HTTP/1.1
content-type: application/json

{
    "idCategory": 12,
    "idSize": 2,
    "items": 10,
    "page": 1,
    "order": { "fullPrice": "ASC"}
    
}